[package]
name = "web-client"
version = "0.1.0"
authors = ["csdietz@google.com"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
gloo-utils = "0.2.0"
log = "0.4.21"
serde_json = "1.0.117"
wasm-bindgen = "0.2.92"
wasm-logger = "0.2.0"
web-common = { path = "../web-common" }
web-sys = "0.3.69"
yew = { version = "0.21", features = ["csr"] }
yew-hooks = "0.3.2"

[lints]
clippy.unit-arg = "allow"
rust.unsafe-op-in-unsafe-fn = "warn"
rust.unused-crate-dependencies = "warn"

[features]
web_client_log_level_info = []
web_client_log_level_debug = []
web_client_log_level_warn = []
web_client_log_level_error = []
web_client_log_level_trace = []

